##**Fiche d'exercices : NumPy (1h30)**

###**Introduction (15 minutes) : Rappel des concepts clés**
Pour bien démarrer, nous allons réviser rapidement les notions de base de NumPy avec des exemples simples.

---



####**1.1. Tableaux NumPy (1-2 minutes)**

Un tableau NumPy est une structure de données optimisée pour les calculs numériques. Contrairement aux listes Python, il permet de réaliser des opérations plus efficacement, notamment sur des grandes quantités de données.

**Exemple :**



In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Résultat : [1 2 3 4 5]


---


####1.2. Création de tableaux (5-6 minutes)
NumPy propose plusieurs méthodes pour créer des tableaux rapidement.
1.  **`np.zeros(shape)`** : Crée un tableau de zéros.

In [ ]:
arr = np.zeros(5)
arr

2.   `np.ones(shape)` : Crée un tableau de uns.

In [ ]:
arr = np.ones(3)
arr

3. `np.full(shape, value)` : Crée un tableau avec une valeur spécifique.

In [ ]:
arr = np.full(4, 7)
arr

4. `np.arange(start, stop, step)` : Crée une séquence avec un pas défini.

In [ ]:
arr = np.arange(0, 10, 2)
arr

5. `np.linspace(start, stop, num)` : Crée une séquence de points également espacés.

In [ ]:
arr = np.linspace(0, 1, 5)
arr

---

####**1.3. Création de matrices (3-4 minutes)**

Les matrices sont des tableaux 2D. En NumPy, voici comment créer des matrices :

1. `np.zeros((3, 3))` : Crée une matrice 3x3 de zéros.

In [ ]:
arr_2d = np.zeros((3, 3))
arr_2d

2. `np.ones((2, 4))` : Crée une matrice 2x4 de uns.

In [ ]:
arr_2d = np.ones((2, 4))
arr_2d

3. `np.arange(9).reshape(3, 3)` : Crée une matrice 3x3 avec des valeurs de 0 à 8.

In [ ]:
arr_2d = np.arange(9).reshape(3, 3)
arr_2d

4. `np.eye(3)` : Crée une matrice identité 3x3.

In [ ]:
arr_2d = np.eye(3)
arr_2d

---

####**1.4. Indexation et slicing (3-4 minutes)**
Indexation permet d'accéder à un élément spécifique, et slicing permet de sélectionner des sous-ensembles de valeurs.
*   Exemple d'indexation :

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])  # Output attendu : 30


*   Exemple de slicing :



In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Output attendu : [20 30 40]


*   Slicing sur une matrice 2D :


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, :])  # Output attendu : [4 5 6]

####**1.5. Opérations mathématiques sur les tableaux (3-4 minutes)**
NumPy permet de réaliser des opérations mathématiques de manière rapide et efficace sur des tableaux entiers.
*   Somme des éléments : `np.sum()`



In [ ]:
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))  # Output attendu : 10


*   Moyenne des éléments : np.mean()



In [ ]:
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # Output attendu : 2.5

*   Écart-type des éléments : np.std()

In [ ]:
arr = np.array([1, 2, 3, 4])
print(np.std(arr))  # Output attendu : 1.11803398875

##**Exercices pratiques (1h15)**
Maintenant que vous avez révisé les concepts clés, passons à la partie pratique. Complétez les sections de code en suivant les indications.

---

1. Créez un tableau de 10 zéros.

*   Code :


In [14]:
# Code ici


Output:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Créez un tableau de 10 uns.
*   Code




In [15]:
# Code ici


Output: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

3. Créez un tableau de 10 de 5.
*   Code

In [17]:
# Code ici


Output:

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


4. Créez un tableau contenant les entiers de 10 à 50.
*   Code



In [16]:
# Code ici


Output:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


---

####**Exercice 2 : Manipulation de matrices (10 minutes)**
1. Créez une matrice 3x3 avec des valeurs allant de 0 à 8.

*   Code :


In [ ]:
# Code ici


[[0 1 2]
 [3 4 5]
 [6 7 8]]


2. Créez une matrice identité 3x3.
*   Code :

In [ ]:
# Code ici


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. Utilisez NumPy pour générer un nombre aléatoire entre 0 et 1.
*   Code :


In [ ]:
# Code ici


0.528847256223914


4. Générez un tableau de 25 nombres aléatoires selon une distribution normale standard.
*   Code :

In [ ]:
# Code ici


[ 0.123  1.234 -0.432 ... ]


---


###Exercice 3 : Indexation et slicing (15 minutes)
À partir de la matrice suivante :


In [ ]:
mat = np.arange(1, 26).reshape(5, 5)

1. Sélectionnez les éléments de la 3e à la dernière ligne, de la 2e à la dernière colonne.
*   Code



In [ ]:
# Code ici


Output attendu:


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

2. Sélectionnez l'élément à la position [3, 4].


*   Code



In [ ]:
# Code ici


Output attendu :

20

3. Sélectionnez les trois premiers éléments de la 2e colonne.


*   Code



In [ ]:
# Code ici


Output attendu :

[2 7 12]

---


###Exercice 4 : Opérations mathématiques (15 minutes)
1. Obtenez la somme de toutes les valeurs dans mat.

*   Code :


In [ ]:
# Code ici


Output attendu :
325

2. Calculez l'écart-type des valeurs dans `mat`.
*   Code :


In [ ]:
# Code ici


Output attendu :

7.211102550927978

3. Obtenez la somme de chaque colonne dans `mat`.
*   Code :




In [19]:
# Code ici


Output attendu:
[55. 60. 65. 70. 75.]

---

###**Exercice 5 : Manipulation aléatoire (15 minutes)**
1. Créez un tableau de 100 valeurs comprises entre 0.01 et 1.00, réparties uniformément. Mélangez ensuite ces valeurs aléatoirement et placez-les dans une matrice 10x10.

*   Code :


In [ ]:
# Code ici


[[0.45 0.13 ...] [0.23 ...] ... ]


2. Créez un tableau de 20 points également espacés entre 0 et 1.

*   Code :

In [ ]:
# Code ici


Output attendu :
[0.   0.05 ... 1.  ]

###Synthèse (5 minutes)
Rappelez-vous des concepts suivants :

1. La différence entre `np.arange()` et `np.linspace()`.
2. Comment utiliser `reshape()` pour manipuler les dimensions des tableaux.
3. La génération de nombres aléatoires avec `np.random`.